name: backend-ci
on:
  push:
    branches: [main]
    paths:
      - "backend/**"
jobs:
  backend-build:
    runs-on: ubuntu-latest
    env:
      PORT: 5000
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
        working-directory: backend
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: athulrameshnr/shopping-cart-backend:ci
