name: Frontend ci

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: http://localhost:5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: frontend
      - run: npm test
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: athulrameshnr/shopping-cart-frontend:ci
